//! The Layover HTTP surface, generated from `api/openapi.yaml`.
//!
//! @generated by `cargo xtask generate-api`. Do not edit by hand: `cargo xtask verify`
//! regenerates this file and fails if the result differs, so an edit here is reverted
//! rather than kept. Change the specification instead.
//!
//! Source: Layover Tower API v1.8.0

#![allow(clippy::too_many_lines)]

use axum::response::IntoResponse as _;
use serde::{Deserialize, Serialize};

use crate::EventStream;

/// Whether an agent is declared to write to the shared workspace or only to read it. Declared,
/// not yet enforced: every agent runs in its working directory whatever this says.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Access {
    /// `read-only`
    #[serde(rename = "read-only")]
    ReadOnly,
    /// `read-write`
    #[serde(rename = "read-write")]
    ReadWrite,
}

/// One configured agent.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Agent {
    /// Whether the agent writes to the shared workspace.
    pub access: Access,
    /// The context-window tier, such as `long_context`: the agent's `context` (or
    /// `[defaults] context`) where its runner carries a `{context}` placeholder, or a
    /// `--context` its runner's command fixes. Null when the command line sets none.
    #[serde(default)]
    pub context: Option<String>,
    /// One line saying what the agent is.
    #[serde(default)]
    pub description: Option<String>,
    /// Whether a human may send flights straight to this agent.
    pub entry: bool,
    /// The model this agent runs on: read from the command line Layover will run, so a model
    /// fixed in the runner's command is reported as readily as one the agent declares. Null
    /// when the command line names none and the CLI picks its own.
    #[serde(default)]
    pub model: Option<String>,
    /// The key the agent is declared under, and what routes refer to.
    pub name: String,
    /// A longer statement of when to route work here.
    #[serde(default)]
    pub purpose: Option<String>,
    /// How hard the model is asked to reason: the agent's `effort` (or `[defaults] effort`)
    /// where its runner carries an `{effort}` placeholder, or a `--reasoning-effort` its
    /// runner's command fixes. Null when the command line sets none.
    #[serde(default)]
    pub reasoning_effort: Option<String>,
    /// Whether the agent is pinned resident rather than transient.
    pub resident: bool,
    /// Which runner invokes this agent's CLI.
    #[serde(default)]
    pub runner: Option<String>,
}

/// The factory's agents and the edges between them.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AgentList {
    /// Every configured agent.
    pub agents: Vec<Agent>,
    /// The route map.
    pub routes: Vec<Route>,
}

/// What kind of thing an agent is stuck on. Coarse on purpose: the point is to make "half my
/// runs are stuck on credentials" visible at a glance, with the detail in the prose.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Blocker {
    /// `access`
    #[serde(rename = "access")]
    Access,
    /// `tooling`
    #[serde(rename = "tooling")]
    Tooling,
    /// `ambiguity`
    #[serde(rename = "ambiguity")]
    Ambiguity,
    /// `environment`
    #[serde(rename = "environment")]
    Environment,
    /// `decision`
    #[serde(rename = "decision")]
    Decision,
    /// `other`
    #[serde(rename = "other")]
    Other,
}

/// One named slice of spend, such as an agent or a model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CostBucket {
    /// The agent or model this slice belongs to.
    pub name: String,
    /// Totals for this slice.
    pub summary: CostSummary,
}

/// Where the factory's money went.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CostReport {
    /// Spend per agent, most expensive first.
    pub by_agent: Vec<CostBucket>,
    /// Spend per model, most expensive first. Runs with no reported model are omitted.
    pub by_model: Vec<CostBucket>,
    /// Spend per workflow, most expensive first. The breakdown a factory with several
    /// pipelines actually needs: per-agent totals cannot answer "what does the nightly sweep
    /// cost" once an agent belongs to more than one workflow, and most of them do.
    pub by_pipeline: Vec<CostBucket>,
    /// The factory-wide ceiling and what is left of it.
    pub reserve: ReserveState,
    /// The period these totals cover, including the zone it was reckoned in and whether it
    /// outruns retention. Part of the number, not decoration.
    pub span: WindowSpan,
    /// Totals across every run in scope.
    pub total: CostSummary,
}

/// Where a cost figure came from, worst-first. `reported` is dollars the runner printed;
/// `copilot_credits` is the Copilot AI credits a run reported, priced at the factory's
/// `[copilot] usd_per_credit` — measured, like `reported`, and both debit Fuel and draw on the
/// Reserve. `rate_card` was derived from token counts and published prices; `unreported`
/// means the runner said nothing, so the figure is zero and means nothing.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CostSource {
    /// `reported`
    #[serde(rename = "reported")]
    Reported,
    /// `copilot_credits`
    #[serde(rename = "copilot_credits")]
    CopilotCredits,
    /// `rate_card`
    #[serde(rename = "rate_card")]
    RateCard,
    /// `unreported`
    #[serde(rename = "unreported")]
    Unreported,
}

/// Totals over some set of runs, carrying their own confidence.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CostSummary {
    /// The weakest source contributing to this total.
    pub confidence: CostSource,
    /// Runs priced from the Copilot AI credits they reported. Counted as measured.
    pub credit_runs: i32,
    /// Runs priced from a rate card rather than measured.
    pub estimated_runs: i32,
    /// Fraction of runs whose cost was measured — dollars the runner printed, or Copilot
    /// credits it reported — 0.0 to 1.0.
    pub measured_share: f64,
    /// How many runs contributed.
    pub runs: i32,
    /// Runs whose runner reported no cost at all.
    pub unreported_runs: i32,
    /// Total tokens.
    pub usage: TokenUsage,
    /// Total cost in US dollars.
    pub usd: f64,
}

/// A period to report over.
///
/// Two kinds, and the difference matters. `today` and `month_to_date` are **calendar** windows: they
/// begin at local midnight, so which instant that is depends on the Tower's time zone. The
/// rest are **rolling**: a fixed number of hours ending now, identical everywhere.
///
/// Conflating the two is not theoretical. Gating spend on a UTC day boundary while reporting
/// the ledger in local time lets a factory spend one day's money twice, and the bug is
/// invisible until it matters.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CostWindow {
    /// `today`
    #[serde(rename = "today")]
    Today,
    /// `last_24h`
    #[serde(rename = "last_24h")]
    Last24h,
    /// `last_7d`
    #[serde(rename = "last_7d")]
    Last7d,
    /// `last_30d`
    #[serde(rename = "last_30d")]
    Last30d,
    /// `month_to_date`
    #[serde(rename = "month_to_date")]
    MonthToDate,
    /// `last_90d`
    #[serde(rename = "last_90d")]
    Last90d,
    /// `all_time`
    #[serde(rename = "all_time")]
    AllTime,
}

/// A boolean parameter a pipeline accepts at trigger time.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Flag {
    /// Value used when the trigger does not set the flag.
    pub default: bool,
    /// What turning this flag on actually does.
    #[serde(default)]
    pub description: Option<String>,
    /// The name a prompt tests with `@include(name)`.
    pub name: String,
}

/// A flag resolved to the value one run will see. Distinct from `Flag`, which declares what a pipeline accepts: a declaration carries a default, and reporting that default back as though it were the operator's choice would hide the difference between a flag left alone and a flag deliberately set to the same value.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FlagValue {
    /// The name a prompt tests with `@include(name)`.
    pub name: String,
    /// The value this run will see.
    pub value: bool,
}

/// Confirmation that work has been started.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FlightAccepted {
    /// Identifier of the flight that was created.
    pub flight_id: String,
    /// Identifier of the new chain, which carries Hops and Fuel.
    pub itinerary_id: String,
    /// The agent the flight was addressed to.
    pub to: String,
}

/// Whether everything is halted.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GroundStop {
    /// True when no new work may start.
    pub engaged: bool,
    /// When the Ground Stop was engaged.
    #[serde(default)]
    pub since: Option<String>,
}

/// Whether the Tower is up and whether it is allowed to do anything.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Health {
    /// True when a Ground Stop is engaged and no new work may start.
    pub ground_stop: bool,
    /// Always `ok`; failure is signalled by not answering at all.
    pub status: Status,
    /// The Tower's own version.
    pub version: String,
}

/// What a chain is waiting for a person to answer.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HelpAsk {
    /// The agent that asked.
    pub agent: String,
    /// The run that asked, which is what a reply names.
    pub run_id: String,
    /// What it asked, in one line.
    pub summary: String,
}

/// Matching help requests, most recent first.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HelpList {
    /// How many of them nobody has dealt with.
    pub open: i32,
    /// The requests.
    pub requests: Vec<HelpRequest>,
}

/// The work a reply started.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HelpReplied {
    /// How many open requests the reply answered.
    pub answered: i32,
    /// The flags it carries.
    #[serde(default)]
    pub flags: Option<std::collections::BTreeMap<String, bool>>,
    /// The flight that was queued.
    pub flight_id: String,
    /// The new chain.
    pub itinerary_id: String,
    /// The workflow the work continues in.
    #[serde(default)]
    pub pipeline: Option<String>,
    /// The agent that asked, which the flight is for.
    pub to: String,
}

/// A person's answer to a help request, and the chain it started.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HelpReply {
    /// When.
    pub at: String,
    /// What they said, verbatim.
    pub body: String,
    /// Who replied, as they gave it, or the account the dashboard runs as.
    pub by: String,
    /// The chain the reply started.
    pub itinerary_id: String,
}

/// An answer to a run's help requests.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HelpReplyRequest {
    /// The answer, sent to the agent verbatim below a fixed first line.
    pub body: String,
    /// Who is replying. Defaults to the account the dashboard runs as.
    #[serde(default)]
    pub by: Option<String>,
    /// The flags the chain that asked had, for a request filed before Layover recorded them.
    /// Refused for any other.
    #[serde(default)]
    pub flags: Option<std::collections::BTreeMap<String, bool>>,
    /// The run whose open requests this answers.
    pub run_id: String,
}

/// One agent asking a human for something.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HelpRequest {
    /// Who is asking.
    pub agent: String,
    /// When it was raised.
    pub at: String,
    /// What kind of thing is in the way.
    pub blocker: Blocker,
    /// What was tried, what happened, and what is needed.
    pub detail: String,
    /// Whether this stopped the work or merely limited it. An agent can finish its task and
    /// still have been unable to check something; that is worth reporting and is not an
    /// outage.
    pub fatal: bool,
    /// The flags of the chain that raised it, which a reply carries. Absent when the request
    /// was filed before Layover recorded them — a reply must then say what they were.
    #[serde(default)]
    pub flags: Option<std::collections::BTreeMap<String, bool>>,
    /// The chain it belonged to.
    pub itinerary_id: String,
    /// The workflow whose run raised it, derived from the itinerary rather than stored on the
    /// request. Null when no run for that itinerary is still in history, which retention can
    /// cause at the far edge of the window.
    #[serde(default)]
    pub pipeline: Option<String>,
    /// How a person answered it, when they replied rather than only resolving it.
    #[serde(default)]
    pub reply: Option<HelpReply>,
    /// When a human marked it dealt with. Null while it is still open.
    #[serde(default)]
    pub resolved_at: Option<String>,
    /// The run that raised it.
    pub run_id: String,
    /// One line, for a list.
    pub summary: String,
}

/// The result of resolving.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HelpResolved {
    /// How many open requests were marked. Zero is not an error: somebody else may have
    /// resolved them, or the narrowing may have matched nothing.
    pub resolved: i32,
}

/// How much applying a learning would change a future run. Self-assessed, and therefore used
/// for display and triage only — never to decide whether a learning applies.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Impact {
    /// `low`
    #[serde(rename = "low")]
    Low,
    /// `medium`
    #[serde(rename = "medium")]
    Medium,
    /// `high`
    #[serde(rename = "high")]
    High,
}

/// One causal chain of flights, and the budget it shares.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Itinerary {
    /// Agents that ran in this chain, in the order they first ran.
    #[serde(default)]
    pub agents: Option<Vec<String>>,
    /// Chains that continue this one, started by replies to its help requests.
    #[serde(default)]
    pub continued_by: Option<Vec<String>>,
    /// The chain this one continues, when a reply to a help request started it.
    #[serde(default)]
    pub continues: Option<String>,
    /// Why a chain is stalled, halted or waiting, when that can be said, or the chain that
    /// continued it.
    #[serde(default)]
    pub detail: Option<String>,
    /// When the last run of the chain ended. Null while it is still working.
    #[serde(default)]
    pub finished_at: Option<String>,
    /// The flags its runs were composed with, which continuing it starts from. Absent for a
    /// chain no workflow opened, and for one whose runs predate their being recorded.
    #[serde(default)]
    pub flags: Option<std::collections::BTreeMap<String, bool>>,
    /// Identifier of the chain.
    pub itinerary_id: String,
    /// False when any run in the chain reported no cost. A total built partly from silence is
    /// a floor, not a figure, and showing it as though it were measured invites planning
    /// against it.
    #[serde(default)]
    pub measured: Option<bool>,
    /// The pipeline it was triggered through, when one was named.
    #[serde(default)]
    pub pipeline: Option<String>,
    /// Agents this chain has work queued for, waiting for a free slot — or, under a Ground
    /// Stop, for it to be released.
    #[serde(default)]
    pub queued: Option<Vec<String>>,
    /// Agents with a run alive in this chain now, which is where the chain is.
    #[serde(default)]
    pub running: Option<Vec<String>>,
    /// How many runs the chain has started.
    pub runs: i32,
    /// When the first run of the chain began, or for a chain with nothing run yet, when its
    /// first flight was queued.
    pub started_at: String,
    /// What became of the chain.
    pub state: ItineraryState,
    /// What the chain has spent, as far as its runners reported.
    pub usd: f64,
    /// What it is waiting for a person to answer, when it is `awaiting_human`.
    #[serde(default)]
    pub waiting_for: Option<HelpAsk>,
}

/// One chain, whole.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ItineraryDetail {
    /// The chain, as `GET /itineraries` lists it.
    pub itinerary: Itinerary,
    /// Its workflow's route map, drawn for this chain: each agent coloured by how it fared
    /// here, a count on any that ran more than once, and the routes its work took marked
    /// `travelled`. The whole factory, for a chain no workflow opened.
    pub map: RouteMap,
    /// Its flights waiting to start, oldest first.
    pub pending: Vec<PendingFlight>,
    /// Every run in it, alive or over, oldest first.
    pub runs: Vec<Run>,
}

/// Chains of work.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ItineraryList {
    /// How many of them are waiting for a person to answer a help request.
    pub awaiting_human: i32,
    /// Chains, most recently started first.
    pub itineraries: Vec<Itinerary>,
    /// How many of them are stalled. Counted separately so the number can be shown without
    /// reading the list, because it is the one that should prompt somebody to look.
    pub stalled: i32,
}

/// What became of a chain.
///
/// `stalled` is the one that matters and the one a list of runs cannot show: every run
/// succeeded, nothing is live, nothing is queued, and nothing will ever happen again. It is
/// the failure mode this whole surface exists to make visible.
///
/// `awaiting_human` looks finished and is not: the chain's last run stopped to ask a person
/// something — a fatal help request, still open — and nothing will run until somebody
/// answers. Resolving the request without replying makes it `finished`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ItineraryState {
    /// `working`
    #[serde(rename = "working")]
    Working,
    /// `finished`
    #[serde(rename = "finished")]
    Finished,
    /// `stalled`
    #[serde(rename = "stalled")]
    Stalled,
    /// `halted`
    #[serde(rename = "halted")]
    Halted,
    /// `awaiting_human`
    #[serde(rename = "awaiting_human")]
    AwaitingHuman,
}

/// The condition under which a rendezvous barrier releases.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Join {
    /// `all`
    #[serde(rename = "all")]
    All,
    /// `any`
    #[serde(rename = "any")]
    Any,
}

/// A person's verdict on a learning.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct JudgeLearningRequest {
    /// The verdict.
    pub state: Judgement,
}

/// What a person decided about a learning that is already in use.
///
/// There is no `provisional` here. A learning starts provisional on its own and becomes
/// confirmed through independent rediscovery; putting one *back* would discard evidence
/// already gathered.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Judgement {
    /// `confirmed`
    #[serde(rename = "confirmed")]
    Confirmed,
    /// `rejected`
    #[serde(rename = "rejected")]
    Rejected,
}

/// Something an agent worked out, with its history.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Learning {
    /// The agent this applies to. Learnings do not cross agents.
    pub agent: String,
    /// When it was first proposed.
    pub first_at: String,
    /// Identifier.
    pub id: String,
    /// The agent's own rating, for triage.
    pub impact: Impact,
    /// When it was most recently proposed.
    pub last_at: String,
    /// How many times it has been independently rediscovered, including the first proposal.
    /// Repeating advice the agent was just shown does not count — an echo is not evidence.
    pub proposals: i32,
    /// Runs before it lapses. Meaningless unless `provisional`.
    pub runs_left: i32,
    /// Where it is in its life.
    pub state: LearningState,
    /// The insight.
    pub text: String,
}

/// Matching learnings.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LearningList {
    /// How many of them are currently given to runs.
    pub active: i32,
    /// The learnings.
    pub learnings: Vec<Learning>,
}

/// Where a learning is in its life. `provisional` applies now and will lapse unless
/// rediscovered; `confirmed` has been rediscovered enough times to be treated as real;
/// `lapsed` is remembered only so a later rediscovery can be recognised as one; `rejected`
/// was refused by a human and never counts again.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LearningState {
    /// `provisional`
    #[serde(rename = "provisional")]
    Provisional,
    /// `confirmed`
    #[serde(rename = "confirmed")]
    Confirmed,
    /// `lapsed`
    #[serde(rename = "lapsed")]
    Lapsed,
    /// `rejected`
    #[serde(rename = "rejected")]
    Rejected,
}

/// A flight that has been asked for and not yet dispatched.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PendingFlight {
    /// The prompt the run will be given.
    pub body: String,
    /// The flags set for this run.
    #[serde(default)]
    pub flags: Option<Vec<FlagValue>>,
    /// Identifier of the queued flight.
    pub flight_id: String,
    /// The chain it will begin.
    pub itinerary_id: String,
    /// The pipeline it was triggered through, when one was named.
    #[serde(default)]
    pub pipeline: Option<String>,
    /// When it was asked for.
    pub queued_at: String,
    /// The agent it is addressed to.
    pub to: String,
}

/// Work waiting to start, and how many runs are alive to take the slots it waits for.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PendingList {
    /// Agent runs alive now, factory-wide: every run a Tower has started and not yet seen
    /// finish. A run left behind by a Tower that went away counts until the next Tower
    /// settles it.
    pub alive_runs: i32,
    /// What is running this queue, or null when nothing in the process serving this API is.
    /// `layover serve` names itself; one started with `--watch-only` says null, because the
    /// queue it shows moves only if a Tower elsewhere, or `layover run`, picks it up. The
    /// dashboard says so rather than showing a queue that looks like it is moving.
    #[serde(default)]
    pub dispatched_by: Option<String>,
    /// How many runs may be alive at once, from `[defaults] max_concurrent_runs`. Queued work
    /// waits for a slot rather than being refused.
    pub max_concurrent_runs: i32,
    /// Queued flights, oldest first.
    pub pending: Vec<PendingFlight>,
}

/// A named entry point into the mesh.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Pipeline {
    /// One line saying what this pipeline is for.
    #[serde(default)]
    pub description: Option<String>,
    /// The agent that receives the first flight.
    pub entry: String,
    /// The boolean parameters this pipeline accepts.
    pub flags: Vec<Flag>,
    /// Shared budget for a chain started here, honouring the entry agent's own `fuel_usd`
    /// where it sets one. Bounds **breadth**, which is the dimension Hops cannot see.
    pub fuel_usd: f64,
    /// Flights a chain started here may make before it is cut. Bounds **depth**: branches
    /// inherit the remaining count rather than splitting it, so this says nothing about how
    /// wide a fan-out spreads.
    pub max_hops: i32,
    /// The key the pipeline is declared under.
    pub name: String,
    /// True when this pipeline picks up booked layovers rather than starting fresh work. A
    /// tick that finds nothing due costs nothing.
    pub resumes: bool,
    /// What starts it.
    pub trigger: Trigger,
    /// Whether instances of this pipeline share a working directory or get one each. A
    /// schedule fires whether or not the last instance finished, so anything reaching a
    /// read-write agent wants its own.
    pub workspace: Workspace,
}

/// Every declared pipeline.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PipelineList {
    /// The pipelines.
    pub pipelines: Vec<Pipeline>,
}

/// An error, shaped after RFC 9457.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Problem {
    /// An explanation specific to this occurrence.
    #[serde(default)]
    pub detail: Option<String>,
    /// The HTTP status code, repeated in the body for clients that lose it.
    pub status: i32,
    /// A short, human-readable summary of the problem.
    pub title: String,
}

/// What an agent wrote about its own run.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Report {
    /// Which agent wrote it.
    pub agent: String,
    /// What the run produced or changed — paths, branch names, pull request identifiers.
    /// Separate from the body so output can be found without reading the prose.
    #[serde(default)]
    pub artifacts: Option<Vec<String>>,
    /// When it was written.
    pub at: String,
    /// The report itself, as the agent wrote it.
    pub body: String,
    /// One line, for a list. What happened, not what was attempted.
    pub headline: String,
    /// The chain it belonged to.
    pub itinerary_id: String,
    /// The run this describes.
    pub run_id: String,
    /// True when the report was longer than the cap and was cut. Worth knowing: otherwise it
    /// reads as though the agent simply stopped there.
    #[serde(default)]
    pub trimmed: Option<bool>,
}

/// The factory-wide spend ceiling. Distinct from Fuel, which bounds one itinerary: a
/// scheduled pipeline mints a fresh itinerary with a fresh Fuel budget on every tick, so
/// only the Reserve bounds the total. The window rolls rather than resetting at midnight.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ReserveState {
    /// Ceiling for the window. Null when no ceiling is enforced.
    #[serde(default)]
    pub cap_usd: Option<f64>,
    /// True when the Reserve is currently refusing new work.
    pub exhausted: bool,
    /// Left before new work is refused. Null when unlimited.
    #[serde(default)]
    pub remaining_usd: Option<f64>,
    /// Spend within the current window.
    pub spent_usd: f64,
    /// How far back the rolling window reaches.
    pub window_hours: i64,
}

/// Which open help requests to mark as dealt with.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ResolveHelpRequest {
    /// Only requests from this agent.
    #[serde(default)]
    pub agent: Option<String>,
    /// Only requests of this kind.
    #[serde(default)]
    pub blocker: Option<Blocker>,
    /// Only requests raised by this run. The narrowest form, and the one a list with a button
    /// beside each row uses.
    #[serde(default)]
    pub run_id: Option<String>,
    /// How far back to look. Defaults to the last 30 days.
    #[serde(default)]
    pub window: Option<CostWindow>,
}

/// One entry of the route map, possibly expanding to several edges.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Route {
    /// Sending agents.
    pub from: Vec<String>,
    /// Set when flights on this edge are parked at a rendezvous barrier.
    #[serde(default)]
    pub join: Option<Join>,
    /// The pipelines whose chains may use this route. Null for a global route, which every
    /// chain may use — what every route meant before scopes existed.
    #[serde(default)]
    pub pipelines: Option<Vec<String>>,
    /// Backstop for a barrier that never completes.
    #[serde(default)]
    pub timeout_sec: Option<i64>,
    /// Receiving agents.
    pub to: Vec<String>,
}

/// The factory drawn as a graph.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RouteMap {
    /// Which file it was generated from.
    #[serde(default)]
    pub config_path: Option<String>,
    /// When the configuration was read.
    pub generated_at: String,
    /// Mermaid `flowchart` source, ready to render.
    pub mermaid: String,
}

/// One supervised CLI execution.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Run {
    /// Which agent was run.
    pub agent: String,
    /// What the run could not get past, when it asked for help. Independent of `status`: an
    /// agent can finish its task and still have been unable to check something. Without it a
    /// blocked run looks exactly like a clean one on a list.
    #[serde(default)]
    pub blocked_on: Option<String>,
    /// The context-window tier the run's command line chose, such as `long_context`. Null
    /// when it chose none, and for runs recorded before Layover kept it.
    #[serde(default)]
    pub context: Option<String>,
    /// Where `cost_usd` came from.
    pub cost_source: CostSource,
    /// Null when the runner reported no cost, which the Tower logs loudly.
    #[serde(default)]
    pub cost_usd: Option<f64>,
    /// Why the run ended, for the outcomes where that is not self-evident. For a failure, how
    /// the process exited and the line of its output most likely to say why — picked from the
    /// transcript, redacted and capped — so a run that failed in one second says what it
    /// said without anybody opening its Hangar.
    #[serde(default)]
    pub detail: Option<String>,
    /// How long the run took. Null while it is still going, and also null if the clock moved
    /// backwards between the two readings — a negative duration on a dashboard is worse than
    /// an absent one, because somebody will average it.
    #[serde(default)]
    pub duration_sec: Option<i64>,
    /// Process exit code, when the process exited on its own and the platform reported one.
    /// Null for a run still going, one that never started, and one the Tower ended for a
    /// timeout or a Ground Stop.
    #[serde(default)]
    pub exit_code: Option<i32>,
    /// When the process exited; null while it is still running.
    #[serde(default)]
    pub finished_at: Option<String>,
    /// The flags the run was composed with, for a chain a workflow opened. Absent otherwise,
    /// and for runs recorded before they were kept.
    #[serde(default)]
    pub flags: Option<std::collections::BTreeMap<String, bool>>,
    /// Hops left when this run was started, mirrored for display only.
    #[serde(default)]
    pub hops_remaining: Option<i32>,
    /// The chain this run belongs to.
    pub itinerary_id: String,
    /// Which model the runner used, when it said.
    #[serde(default)]
    pub model: Option<String>,
    /// The pipeline that started this run's chain, when one did.
    #[serde(default)]
    pub pipeline: Option<String>,
    /// The reasoning effort the run's command line gave the model — from the agent's
    /// `effort`, `[defaults]`, or a value its runner fixes. Null when the command line set
    /// none, and for runs recorded before Layover kept it.
    #[serde(default)]
    pub reasoning_effort: Option<String>,
    /// Identifier of this run.
    pub run_id: String,
    /// The agents whose flights started this run — for a released join, every arrival. Empty
    /// when the work came from outside the mesh: a person, a schedule or a resumed layover.
    /// Absent when it was not recorded: by an earlier release, for a join restarted after the
    /// Tower that released it went away, or for a run the Reserve refused.
    #[serde(default)]
    pub sent_by: Option<Vec<String>>,
    /// When the process was spawned.
    pub started_at: String,
    /// How it ended, or that it has not.
    pub status: RunStatus,
}

/// Matching runs, newest first.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RunList {
    /// The runs.
    pub runs: Vec<Run>,
}

/// How a run ended, or that it has not.
///
/// `halted` is deliberately distinct from `failed`: a rail stopping work — Hops, Fuel, the
/// run cap or the Reserve — is the system doing its job, and colouring it like a crash
/// teaches people to ignore the colour. `interrupted` means the run was alive when the Tower
/// went away; it is recoverable, and recovery starts a new run rather than resuming this one.
///
/// There is no `stalled` here. Stalling is something an *itinerary* does when it parks at a
/// barrier that never releases; a run either finishes or does not.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RunStatus {
    /// `running`
    #[serde(rename = "running")]
    Running,
    /// `succeeded`
    #[serde(rename = "succeeded")]
    Succeeded,
    /// `failed`
    #[serde(rename = "failed")]
    Failed,
    /// `timed_out`
    #[serde(rename = "timed_out")]
    TimedOut,
    /// `halted`
    #[serde(rename = "halted")]
    Halted,
    /// `interrupted`
    #[serde(rename = "interrupted")]
    Interrupted,
}

/// One tick of a scheduled pipeline.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ScheduledFire {
    /// When it is due.
    pub at: String,
    /// For a resuming tick, the layovers expected to be picked up by it.
    pub collects: i32,
    /// The pipeline's previous wave is still going, so this tick is skipped unless that
    /// finishes first. Only ever the next tick: what is running later is not known now.
    pub may_skip: bool,
    /// It is already due and has not fired: held by a Ground Stop, or by a Tower busy starting
    /// work. It fires as soon as it can, and the ticks after it count from then.
    pub overdue: bool,
    /// The pipeline that fires.
    pub pipeline: String,
    /// It collects due layovers rather than starting fresh work.
    pub resumes: bool,
}

/// One scheduled pipeline, and when it next fires.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ScheduledWorkflow {
    /// How many ticks are due before `until`. Counted whole up to 10,000; `fires` lists at most
    /// 24 of them, so a one-minute schedule does not bury every other.
    pub fires_in_window: i32,
    /// The most recent of those, if any.
    #[serde(default)]
    pub last_skipped_at: Option<String>,
    /// When its next tick is due, by the Tower's clock. Null when no clock is known in this
    /// process, or for a cron expression that never matches. A time already past is a tick
    /// held back — by a Ground Stop, usually — that fires as soon as it can.
    #[serde(default)]
    pub next_at: Option<String>,
    /// True when it sets `overlap = "allow"`, so a tick starts whatever is running.
    pub overlaps: bool,
    /// The pipeline.
    pub pipeline: String,
    /// True when its ticks collect due layovers rather than starting fresh work.
    pub resumes: bool,
    /// Ticks of it skipped in the last seven days.
    pub skipped_7d: i32,
    /// Its previous wave is queued or running now. Unless that finishes first, its next tick
    /// is skipped.
    pub working: bool,
}

/// Exactly one of `pipeline` and `to` must be given, and flags are only accepted alongside a
/// pipeline, because a pipeline is what declares them.
///
/// Neither is marked required here because JSON Schema cannot state "exactly one of these"
/// in a way this generator supports. The Tower enforces it and answers `400` — so a client
/// that satisfies this schema can still be rejected.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SendFlightRequest {
    /// What the receiving agent is being asked to do.
    pub body: String,
    /// Flag overrides, keyed by flag name. Unset flags take their declared default.
    #[serde(default)]
    pub flags: Option<std::collections::BTreeMap<String, bool>>,
    /// Name of the pipeline to start.
    #[serde(default)]
    pub pipeline: Option<String>,
    /// Name of an `entry = true` agent to send to directly.
    #[serde(default)]
    pub to: Option<String>,
}

/// Why a scheduled tick that came due did not start. `still_working`: the pipeline's previous
/// wave was still queued or running, and it does not set `overlap = "allow"`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SkipReason {
    /// `still_working`
    #[serde(rename = "still_working")]
    StillWorking,
}

/// A scheduled tick that came due and did not start.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SkippedTick {
    /// When the Tower decided not to start it.
    pub at: String,
    /// The pipeline whose tick it was.
    pub pipeline: String,
    /// Why.
    pub reason: SkipReason,
}

/// Liveness of the Tower itself.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Status {
    /// `ok`
    #[serde(rename = "ok")]
    Ok,
}

/// Tokens consumed. Cached reads and writes are counted apart from fresh input because
/// providers price them very differently, and blending them makes any derived cost wrong by
/// whatever the cache hit rate happened to be.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TokenUsage {
    /// Tokens served from the provider's prompt cache.
    pub cache_read: i64,
    /// Tokens written into the provider's prompt cache.
    pub cache_write: i64,
    /// Prompt tokens billed at the input rate.
    pub input: i64,
    /// Generated tokens.
    pub output: i64,
}

/// What starts a pipeline.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Trigger {
    /// Set when the pipeline fires on a five-field cron expression.
    #[serde(default)]
    pub cron: Option<String>,
    /// Set when the pipeline fires on a fixed interval.
    #[serde(default)]
    pub every_seconds: Option<i64>,
    /// Whether a human or a clock starts this pipeline.
    pub kind: TriggerKind,
}

/// Whether a human or a clock starts a pipeline.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TriggerKind {
    /// `manual`
    #[serde(rename = "manual")]
    Manual,
    /// `scheduled`
    #[serde(rename = "scheduled")]
    Scheduled,
}

/// What will start on its own within a window, and the ticks that recently did not.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Upcoming {
    /// What keeps the schedule: the Tower in this process. Null when nothing here does
    /// (`--watch-only`): when ticks fall is then unknown, and `fires` is empty.
    #[serde(default)]
    pub clock: Option<String>,
    /// Ticks due before `until`, soonest first, at most 24 per pipeline.
    pub fires: Vec<ScheduledFire>,
    /// A Ground Stop is engaged, so nothing here fires until it is released.
    pub ground_stop: bool,
    /// Layovers waiting to be picked up, soonest due first.
    pub layovers: Vec<WaitingLayover>,
    /// The moment this was worked out, so "in 20 minutes" is measured from it.
    pub now: String,
    /// Ticks skipped in the last seven days, most recent first, at most 100.
    pub skips: Vec<SkippedTick>,
    /// The end of the window.
    pub until: String,
    /// Every pipeline with a schedule, by name.
    pub workflows: Vec<ScheduledWorkflow>,
}

/// Work an agent set down to be picked up later, and when it will be.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WaitingLayover {
    /// The agent the resumed work goes to.
    pub agent: String,
    /// When it was set down.
    pub booked_at: String,
    /// The chain that set it down.
    pub booked_by: String,
    /// The first tick of a resuming pipeline at or after `due_at`, which is when it will be
    /// picked up unless that tick is skipped. Null when no clock is known in this process, or
    /// when no scheduled pipeline `resumes` — then nothing will ever pick it up.
    #[serde(default)]
    pub collected_at: Option<String>,
    /// The resuming pipeline whose tick that is.
    #[serde(default)]
    pub collected_by: Option<String>,
    /// The soonest it may be picked up.
    pub due_at: String,
    /// Identifier of the layover.
    pub layover_id: String,
    /// The workflow that chain belonged to, when that was recorded.
    #[serde(default)]
    pub pipeline: Option<String>,
    /// What it is waiting for, in the words of the agent that set it down.
    pub waiting_for: String,
}

/// A resolved window, and an honest account of how it was arrived at.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WindowSpan {
    /// True when the start was reckoned against a local midnight.
    pub calendar: bool,
    /// When the period ends, which is the moment it was resolved.
    pub end: String,
    /// A human label, such as "Last 30 days".
    pub label: String,
    /// When the period begins. Null means from the beginning of what is kept.
    #[serde(default)]
    pub start: Option<String>,
    /// True when the period reaches further back than retention keeps, which makes the
    /// totals a lower bound rather than a total.
    pub truncated: bool,
    /// Which window this is.
    pub window: CostWindow,
    /// The IANA zone the start was reckoned in, or null for a rolling window. The absence is
    /// the point: nobody should have to wonder which zone "last 7 days" used.
    #[serde(default)]
    pub zone: Option<String>,
}

/// Whether instances of one pipeline are declared to share a working directory or to get one
/// each. `per-itinerary` is declared, not yet enforced: every instance still works in the
/// shared working directory.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Workspace {
    /// `shared`
    #[serde(rename = "shared")]
    Shared,
    /// `per-itinerary`
    #[serde(rename = "per-itinerary")]
    PerItinerary,
}

/// query parameters for `getCosts`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GetCostsQuery {
    /// The period to total over. Defaults to the last 30 days.
    ///
    /// Note that `today` and `month_to_date` are *calendar* windows and the rest are *rolling* ones.
    /// A rolling window is the same length everywhere; a calendar one begins at local
    /// midnight and therefore depends on where the Tower is standing. The response says
    /// which zone was used, so the figure can be read without having to guess.
    #[serde(default)]
    pub window: Option<CostWindow>,
    /// Narrow the totals, the per-agent and the per-model breakdowns to one workflow.
    ///
    /// `reserve` is deliberately unaffected. The Reserve caps the whole factory, so reporting
    /// it against one workflow's spend would describe a rail that does not exist.
    #[serde(default)]
    pub pipeline: Option<String>,
}

/// path parameters for `cancelFlight`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CancelFlightPath {
    /// Identifier of the queued flight.
    pub flight_id: String,
}

/// query parameters for `getGraph`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GetGraphQuery {
    /// Draw only what this pipeline sets in motion. Omit for the whole factory.
    ///
    /// A factory holds several pipelines and they are genuinely separate workflows — a
    /// nightly sweep has nothing to do with taking a work item to a pull request. Drawn
    /// together they read as one very confused process. An agent belonging to two workflows
    /// appears in both, which is the honest answer.
    #[serde(default)]
    pub pipeline: Option<String>,
}

/// query parameters for `listHelp`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ListHelpQuery {
    /// Only requests from this agent.
    #[serde(default)]
    pub agent: Option<String>,
    /// Only requests raised by a run of this workflow.
    #[serde(default)]
    pub pipeline: Option<String>,
    /// Only requests of this kind.
    #[serde(default)]
    pub blocker: Option<Blocker>,
    /// Only requests nobody has dealt with yet.
    #[serde(default)]
    pub open: Option<bool>,
    /// How far back to look. Defaults to the last 30 days.
    #[serde(default)]
    pub window: Option<CostWindow>,
}

/// query parameters for `listItineraries`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ListItinerariesQuery {
    /// How far back to look. Defaults to the last 24 hours, because a dashboard opening on
    /// ninety days of chains is answering a question nobody asked.
    #[serde(default)]
    pub window: Option<CostWindow>,
    /// Only chains in this state.
    #[serde(default)]
    pub state: Option<ItineraryState>,
}

/// path parameters for `getItinerary`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GetItineraryPath {
    /// Identifier of the chain.
    pub itinerary_id: String,
}

/// query parameters for `listLearnings`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ListLearningsQuery {
    /// Only learnings belonging to this agent.
    #[serde(default)]
    pub agent: Option<String>,
    /// Only learnings in this state.
    #[serde(default)]
    pub state: Option<LearningState>,
}

/// path parameters for `judgeLearning`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct JudgeLearningPath {
    /// Identifier of the learning.
    pub learning_id: String,
}

/// query parameters for `listRuns`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ListRunsQuery {
    /// Return only runs in this state.
    #[serde(default)]
    pub status: Option<RunStatus>,
    /// Return only runs belonging to this itinerary.
    #[serde(default)]
    pub itinerary_id: Option<String>,
    /// Return only runs of this agent.
    #[serde(default)]
    pub agent: Option<String>,
    /// Return only runs whose chain was started by this pipeline.
    #[serde(default)]
    pub pipeline: Option<String>,
    /// How far back to look. Defaults to the last 24 hours, because a dashboard opening on
    /// ninety days of history is answering a question nobody asked.
    #[serde(default)]
    pub window: Option<CostWindow>,
    /// Maximum number of runs to return, newest first.
    #[serde(default)]
    pub limit: Option<i32>,
}

/// path parameters for `getRun`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GetRunPath {
    /// Identifier of the run to fetch.
    pub run_id: String,
}

/// path parameters for `getReport`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GetReportPath {
    /// Identifier of the run.
    pub run_id: String,
}

/// path parameters for `streamRun`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StreamRunPath {
    /// Identifier of the run to stream.
    pub run_id: String,
}

/// query parameters for `streamRun`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StreamRunQuery {
    /// Resume from here: the `id` of the last event received. Omit to start at the beginning.
    #[serde(default)]
    pub after: Option<i64>,
}

/// query parameters for `getUpcoming`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GetUpcomingQuery {
    /// How far ahead to look, in hours. Defaults to 24; held between 1 and 168.
    #[serde(default)]
    pub hours: Option<i32>,
}

/// Everything the Tower must implement to serve this API.
///
/// One method per `operationId`. Adding an operation to `api/openapi.yaml` adds a method
/// here, so an unimplemented endpoint is a compile error rather than a 404 discovered in
/// production.
pub trait Api: Send + Sync + 'static {
    /// Every configured agent and the route map between them.
    ///
    /// This is the UI's graph view, and it is also how a human answers "what can talk to what"
    /// without reading the TOML.
    ///
    /// `GET /agents`
    fn list_agents(&self) -> impl core::future::Future<Output = Result<AgentList, Problem>> + Send;
    /// What the factory has spent, and how much of that is measured.
    ///
    /// A single Fuel figure says whether a chain may continue. This says where the money went —
    /// per agent, per model — and, critically, how much of the total the runners actually
    /// reported rather than Layover inferring it from a rate card.
    ///
    /// Treat `confidence` as part of the number. A total that is mostly measured is still not
    /// measured, so any estimated or unreported run downgrades the whole figure.
    ///
    /// `GET /costs`
    fn get_costs(
        &self,
        query: GetCostsQuery,
    ) -> impl core::future::Future<Output = Result<CostReport, Problem>> + Send;
    /// Flights waiting for something to dispatch them.
    ///
    /// Work that has been asked for and not yet started. Until the supervisor exists this is
    /// everything anybody has triggered; afterwards it is the backlog.
    ///
    /// `GET /flights`
    fn list_pending(
        &self,
    ) -> impl core::future::Future<Output = Result<PendingList, Problem>> + Send;
    /// Start work by sending the first flight of a new itinerary.
    ///
    /// Give either a `pipeline` or a `to`. A pipeline is the normal way in: it names the entry
    /// agent and declares which flags may be set. A bare `to` sends to an agent marked
    /// `entry = true` and accepts no flags.
    ///
    /// **The flight is queued, not run.** `202` means the work is booked and durable; a Tower starts
    /// it as soon as a slot is free. `GET /flights` shows what is waiting, and which Tower will
    /// start it.
    ///
    /// `POST /flights`
    fn send_flight(
        &self,
        body: SendFlightRequest,
    ) -> impl core::future::Future<Output = Result<FlightAccepted, Problem>> + Send;
    /// Take a queued flight back off the queue.
    ///
    /// Only work that has not started can be cancelled. A run that is already going is stopped
    /// with a Ground Stop, which is a different decision with a different blast radius — one
    /// flight versus the whole factory — and conflating them would make the smaller action feel
    /// as dangerous as the larger one.
    ///
    /// `DELETE /flights/{flight_id}`
    fn cancel_flight(
        &self,
        path: CancelFlightPath,
    ) -> impl core::future::Future<Output = Result<PendingList, Problem>> + Send;
    /// The route map as a diagram, with what is happening drawn on it.
    ///
    /// Mermaid source, generated from the configuration as it is on disk right now. Edit
    /// `layover.toml` and reload; the diagram changes with it, because nothing here is baked at
    /// build time.
    ///
    /// Agents currently running, waiting at a barrier, or freshly failed are coloured. An agent
    /// with more than one run alive at once — the same workflow triggered twice, say — carries a
    /// count such as `×2`. An edge into a joined agent from a sender the barrier does not name is
    /// drawn as bypassing it, which is what actually happens. To see one chain on its own, use
    /// `GET /itineraries/{itinerary_id}`.
    ///
    /// `GET /graph`
    fn get_graph(
        &self,
        query: GetGraphQuery,
    ) -> impl core::future::Future<Output = Result<RouteMap, Problem>> + Send;
    /// Halt everything.
    ///
    /// Ground Stop is a file on disk rather than in-memory state, so it survives a Tower crash
    /// and can be set by hand when nothing else is responding.
    ///
    /// `POST /ground-stop`
    fn engage_ground_stop(
        &self,
    ) -> impl core::future::Future<Output = Result<GroundStop, Problem>> + Send;
    /// Resume.
    ///
    /// `DELETE /ground-stop`
    fn release_ground_stop(
        &self,
    ) -> impl core::future::Future<Output = Result<GroundStop, Problem>> + Send;
    /// Liveness, version and whether a Ground Stop is engaged.
    ///
    /// `GET /health`
    fn get_health(&self) -> impl core::future::Future<Output = Result<Health, Problem>> + Send;
    /// What agents are stuck on.
    ///
    /// A lights-out factory's worst failure is not a crash — a crash is loud. It is an agent that
    /// quietly cannot do what it was asked, produces something plausible anyway, and passes it
    /// downstream. This is the channel that stops that being invisible.
    ///
    /// Measured against a working prototype, five of six requests were permission or access
    /// failures, so `access` is worth filtering for first.
    ///
    /// `GET /help`
    fn list_help(
        &self,
        query: ListHelpQuery,
    ) -> impl core::future::Future<Output = Result<HelpList, Problem>> + Send;
    /// Answer a help request, and continue the work it stopped.
    ///
    /// Answers every open request the run raised. Queues a flight to the agent that asked, from a
    /// person, starting a **new chain** with a fresh budget — the chain that asked is over — in
    /// the same workflow, with the same flags and the same routes as the chain that asked. Never
    /// the workflow's defaults: continuing a chain that was allowed to publish as one that may not
    /// is the silent downgrade this exists to avoid.
    ///
    /// The agent is told `In reply to your help request <run_id> (<summary>)`, then the body,
    /// verbatim. The requests are marked dealt with, recording who replied, what they said and the
    /// new chain, which records the chain it continues.
    ///
    /// A request filed before Layover recorded its chain's flags does not know them. For one of
    /// those whose workflow declares flags, `flags` must say what they were, and the reply is
    /// refused with `409` until it does. For any other request `flags` is refused: the recorded
    /// flags are carried, and continuing a chain with different ones is what `POST /flights`
    /// is for.
    ///
    /// Needs the same token as a trigger, and a Ground Stop refuses it like one.
    ///
    /// `POST /help/reply`
    fn reply_help(
        &self,
        body: HelpReplyRequest,
    ) -> impl core::future::Future<Output = Result<HelpReplied, Problem>> + Send;
    /// Mark help requests as dealt with.
    ///
    /// Resolving says *the blocker is gone*, not *I have read this*. An agent that raises the same
    /// problem on its next run will raise it again, which is the point: a list that clears itself
    /// on being looked at stops being evidence of anything.
    ///
    /// Narrow by agent, blocker or run. An empty body resolves every open request in the window,
    /// which is what you want after fixing something that stopped everything.
    ///
    /// `POST /help/resolve`
    fn resolve_help(
        &self,
        body: ResolveHelpRequest,
    ) -> impl core::future::Future<Output = Result<HelpResolved, Problem>> + Send;
    /// Chains of work, and what became of each.
    ///
    /// A run is one agent doing one thing; an itinerary is the whole causal chain and the budget
    /// it shares. The distinction matters most when something goes wrong: a chain can be *stalled*
    /// — every run in it succeeded and nothing will ever happen again — and a list of runs cannot
    /// show that, because there is no failed run to point at.
    ///
    /// A chain is listed from the moment its first flight is queued: `working`, with no runs yet,
    /// and `queued` naming the agent it waits for. Triggering one workflow several times while
    /// every slot is taken would otherwise show some of those chains and silently not the rest.
    ///
    /// `GET /itineraries`
    fn list_itineraries(
        &self,
        query: ListItinerariesQuery,
    ) -> impl core::future::Future<Output = Result<ItineraryList, Problem>> + Send;
    /// One chain, whole — its runs, what it is waiting for, and its route map.
    ///
    /// Everything one trigger caused, read together: the chain as `GET /itineraries` lists it,
    /// every run in it oldest first with who sent each one, the flights it has queued, and its
    /// workflow's route map coloured by this chain alone.
    ///
    /// Several chains of one workflow run at once, and the workflow's map colours an agent while
    /// *any* of them runs it. This one does not: an agent is `done`, `running`, `failed` or
    /// `queued` for what happened *in this chain*, carries `×2` when it ran twice here, and the
    /// routes the chain's work actually took are marked `travelled`.
    ///
    /// Read from the moment the chain began, whatever its age, as far back as retention keeps.
    ///
    /// `GET /itineraries/{itinerary_id}`
    fn get_itinerary(
        &self,
        path: GetItineraryPath,
    ) -> impl core::future::Future<Output = Result<ItineraryDetail, Problem>> + Send;
    /// What agents have worked out, and how well established it is.
    ///
    /// A learning applies as soon as it is proposed and expires unless later runs arrive at it
    /// independently. There is no approval queue, deliberately: a sibling project built one and
    /// after 22 days held 88 learnings, none ever approved, so not one had ever reached a run.
    ///
    /// A learning becomes permanent through independent rediscovery, which is evidence, rather
    /// than through its `impact` rating, which is the agent's own claim about its own work.
    ///
    /// `GET /learnings`
    fn list_learnings(
        &self,
        query: ListLearningsQuery,
    ) -> impl core::future::Future<Output = Result<LearningList, Problem>> + Send;
    /// Settle a learning, either way.
    ///
    /// **This is not an approval queue.** A learning applies from the moment it is proposed, and
    /// nothing is waiting on you. A sibling project gated learnings behind approval and after 22
    /// days held 88 of them, none ever approved, so not one had ever reached a run.
    ///
    /// This is the override. `confirmed` means "this is real, keep it indefinitely" and spares it
    /// from lapsing. `rejected` means "this is wrong, stop applying it" and takes it out of every
    /// future run. Both are judgements a person makes about something already in use, not
    /// permission for it to start being used.
    ///
    /// `PATCH /learnings/{learning_id}`
    fn judge_learning(
        &self,
        path: JudgeLearningPath,
        body: JudgeLearningRequest,
    ) -> impl core::future::Future<Output = Result<Learning, Problem>> + Send;
    /// Every declared pipeline, its trigger and the flags it accepts.
    ///
    /// `GET /pipelines`
    fn list_pipelines(
        &self,
    ) -> impl core::future::Future<Output = Result<PipelineList, Problem>> + Send;
    /// Runs, live and historical.
    ///
    /// Runs alive now come first, as `running`, from the live records the Tower keeps while a run
    /// is going — whichever process started it. History holds a run only once it has ended.
    ///
    /// `GET /runs`
    fn list_runs(
        &self,
        query: ListRunsQuery,
    ) -> impl core::future::Future<Output = Result<RunList, Problem>> + Send;
    /// One run, including how it ended.
    ///
    /// `GET /runs/{run_id}`
    fn get_run(
        &self,
        path: GetRunPath,
    ) -> impl core::future::Future<Output = Result<Run, Problem>> + Send;
    /// What the agent wrote about this run.
    ///
    /// A transcript is not a report: it contains every approach the agent abandoned, and reading
    /// one to find out what happened is slower than doing the work again. This is the agent''s own
    /// account of what it concluded.
    ///
    /// `GET /runs/{run_id}/report`
    fn get_report(
        &self,
        path: GetReportPath,
    ) -> impl core::future::Future<Output = Result<Report, Problem>> + Send;
    /// What a run's CLI printed, rendered as a terminal would show it, live.
    ///
    /// Read-only. Follows the run's transcript in its Hangar from the start — or from `after` —
    /// and keeps following it while the run is alive. For a run that is over it sends the whole
    /// transcript and closes, so the same request replays how a finished run reached its
    /// conclusion.
    ///
    /// The transcript is rendered rather than sent raw: a Copilot or Claude Code run writes one
    /// JSON event per line, most of them token-by-token deltas of text that arrives again whole.
    /// What is sent is what the CLI would show a person — the prompt's first lines, reasoning,
    /// each tool call and a few lines of what it returned, what the agent said — redacted like a
    /// failure detail and cut to size. Output in no known dialect is sent as written.
    ///
    /// Three events, each with an `id` saying how far the transcript was read:
    ///
    /// - `entry` — `{"kind", "text", "at", "closes"}`. `kind` is one of `prompt`, `think`,
    ///   `say`, `tool`, `done`, `failed`, `info`, `raw`. `at` is when the CLI said it happened,
    ///   or null. `closes` names the partial this entry finishes, or is null.
    /// - `partial` — `{"id", "kind", "text"}`: the end of text still arriving. Empty `text` takes
    ///   it away.
    /// - `end` — `{"status", "detail"}` from history, once the run is over; `"missing": true`
    ///   when no transcript was kept. Sent once, last.
    ///
    /// `GET /runs/{run_id}/stream`
    fn stream_run(
        &self,
        path: StreamRunPath,
        query: StreamRunQuery,
    ) -> impl core::future::Future<Output = Result<EventStream, Problem>> + Send;
    /// What will start on its own, and the scheduled ticks that did not.
    ///
    /// Work nobody has to trigger: every tick of a scheduled pipeline due within the window, and
    /// every layover waiting to be picked up, with the tick expected to collect it. Beside them,
    /// the ticks skipped in the last seven days because the pipeline's previous wave was still
    /// going — a schedule that skips every tick looks, from its runs alone, like one that is
    /// running fine.
    ///
    /// When a tick comes due is known only to the Tower that keeps the clock, because an `every`
    /// schedule is counted from when that Tower started. A dashboard with no Tower in its process
    /// (`--watch-only`) says so with a null `clock` and lists no ticks, rather than guessing.
    ///
    /// Work already queued is not here: `GET /flights` lists it, oldest first, which is the order
    /// it starts in.
    ///
    /// `GET /upcoming`
    fn get_upcoming(
        &self,
        query: GetUpcomingQuery,
    ) -> impl core::future::Future<Output = Result<Upcoming, Problem>> + Send;
}

/// Builds the axum router for this API.
///
/// Routes come straight from the specification, so a path can only exist here if it
/// exists there.
pub fn router<A: Api>(api: std::sync::Arc<A>) -> axum::Router {
    axum::Router::new()
        .route("/agents", axum::routing::get(handle_list_agents::<A>))
        .route("/costs", axum::routing::get(handle_get_costs::<A>))
        .route(
            "/flights",
            axum::routing::get(handle_list_pending::<A>).post(handle_send_flight::<A>),
        )
        .route(
            "/flights/{flight_id}",
            axum::routing::delete(handle_cancel_flight::<A>),
        )
        .route("/graph", axum::routing::get(handle_get_graph::<A>))
        .route(
            "/ground-stop",
            axum::routing::post(handle_engage_ground_stop::<A>)
                .delete(handle_release_ground_stop::<A>),
        )
        .route("/health", axum::routing::get(handle_get_health::<A>))
        .route("/help", axum::routing::get(handle_list_help::<A>))
        .route("/help/reply", axum::routing::post(handle_reply_help::<A>))
        .route(
            "/help/resolve",
            axum::routing::post(handle_resolve_help::<A>),
        )
        .route(
            "/itineraries",
            axum::routing::get(handle_list_itineraries::<A>),
        )
        .route(
            "/itineraries/{itinerary_id}",
            axum::routing::get(handle_get_itinerary::<A>),
        )
        .route("/learnings", axum::routing::get(handle_list_learnings::<A>))
        .route(
            "/learnings/{learning_id}",
            axum::routing::patch(handle_judge_learning::<A>),
        )
        .route("/pipelines", axum::routing::get(handle_list_pipelines::<A>))
        .route("/runs", axum::routing::get(handle_list_runs::<A>))
        .route("/runs/{run_id}", axum::routing::get(handle_get_run::<A>))
        .route(
            "/runs/{run_id}/report",
            axum::routing::get(handle_get_report::<A>),
        )
        .route(
            "/runs/{run_id}/stream",
            axum::routing::get(handle_stream_run::<A>),
        )
        .route("/upcoming", axum::routing::get(handle_get_upcoming::<A>))
        .with_state(api)
}

async fn handle_list_agents<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
) -> axum::response::Response {
    match api.list_agents().await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_get_costs<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
    axum::extract::Query(query): axum::extract::Query<GetCostsQuery>,
) -> axum::response::Response {
    match api.get_costs(query).await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_list_pending<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
) -> axum::response::Response {
    match api.list_pending().await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_send_flight<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
    axum::Json(body): axum::Json<SendFlightRequest>,
) -> axum::response::Response {
    match api.send_flight(body).await {
        Ok(value) => (axum::http::StatusCode::ACCEPTED, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_cancel_flight<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
    axum::extract::Path(path): axum::extract::Path<CancelFlightPath>,
) -> axum::response::Response {
    match api.cancel_flight(path).await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_get_graph<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
    axum::extract::Query(query): axum::extract::Query<GetGraphQuery>,
) -> axum::response::Response {
    match api.get_graph(query).await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_engage_ground_stop<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
) -> axum::response::Response {
    match api.engage_ground_stop().await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_release_ground_stop<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
) -> axum::response::Response {
    match api.release_ground_stop().await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_get_health<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
) -> axum::response::Response {
    match api.get_health().await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_list_help<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
    axum::extract::Query(query): axum::extract::Query<ListHelpQuery>,
) -> axum::response::Response {
    match api.list_help(query).await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_reply_help<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
    axum::Json(body): axum::Json<HelpReplyRequest>,
) -> axum::response::Response {
    match api.reply_help(body).await {
        Ok(value) => (axum::http::StatusCode::ACCEPTED, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_resolve_help<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
    axum::Json(body): axum::Json<ResolveHelpRequest>,
) -> axum::response::Response {
    match api.resolve_help(body).await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_list_itineraries<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
    axum::extract::Query(query): axum::extract::Query<ListItinerariesQuery>,
) -> axum::response::Response {
    match api.list_itineraries(query).await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_get_itinerary<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
    axum::extract::Path(path): axum::extract::Path<GetItineraryPath>,
) -> axum::response::Response {
    match api.get_itinerary(path).await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_list_learnings<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
    axum::extract::Query(query): axum::extract::Query<ListLearningsQuery>,
) -> axum::response::Response {
    match api.list_learnings(query).await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_judge_learning<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
    axum::extract::Path(path): axum::extract::Path<JudgeLearningPath>,
    axum::Json(body): axum::Json<JudgeLearningRequest>,
) -> axum::response::Response {
    match api.judge_learning(path, body).await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_list_pipelines<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
) -> axum::response::Response {
    match api.list_pipelines().await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_list_runs<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
    axum::extract::Query(query): axum::extract::Query<ListRunsQuery>,
) -> axum::response::Response {
    match api.list_runs(query).await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_get_run<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
    axum::extract::Path(path): axum::extract::Path<GetRunPath>,
) -> axum::response::Response {
    match api.get_run(path).await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_get_report<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
    axum::extract::Path(path): axum::extract::Path<GetReportPath>,
) -> axum::response::Response {
    match api.get_report(path).await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_stream_run<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
    axum::extract::Path(path): axum::extract::Path<StreamRunPath>,
    axum::extract::Query(query): axum::extract::Query<StreamRunQuery>,
) -> axum::response::Response {
    match api.stream_run(path, query).await {
        Ok(stream) => stream.into_response(),
        Err(problem) => problem.into_response(),
    }
}

async fn handle_get_upcoming<A: Api>(
    axum::extract::State(api): axum::extract::State<std::sync::Arc<A>>,
    axum::extract::Query(query): axum::extract::Query<GetUpcomingQuery>,
) -> axum::response::Response {
    match api.get_upcoming(query).await {
        Ok(value) => (axum::http::StatusCode::OK, axum::Json(value)).into_response(),
        Err(problem) => problem.into_response(),
    }
}

/// Every operation the specification declares, as (method, path, operationId).
///
/// Exposed so tests can assert the router and the specification agree.
pub const OPERATIONS: [(&str, &str, &str); 22] = [
    ("GET", "/agents", "listAgents"),
    ("GET", "/costs", "getCosts"),
    ("GET", "/flights", "listPending"),
    ("POST", "/flights", "sendFlight"),
    ("DELETE", "/flights/{flight_id}", "cancelFlight"),
    ("GET", "/graph", "getGraph"),
    ("POST", "/ground-stop", "engageGroundStop"),
    ("DELETE", "/ground-stop", "releaseGroundStop"),
    ("GET", "/health", "getHealth"),
    ("GET", "/help", "listHelp"),
    ("POST", "/help/reply", "replyHelp"),
    ("POST", "/help/resolve", "resolveHelp"),
    ("GET", "/itineraries", "listItineraries"),
    ("GET", "/itineraries/{itinerary_id}", "getItinerary"),
    ("GET", "/learnings", "listLearnings"),
    ("PATCH", "/learnings/{learning_id}", "judgeLearning"),
    ("GET", "/pipelines", "listPipelines"),
    ("GET", "/runs", "listRuns"),
    ("GET", "/runs/{run_id}", "getRun"),
    ("GET", "/runs/{run_id}/report", "getReport"),
    ("GET", "/runs/{run_id}/stream", "streamRun"),
    ("GET", "/upcoming", "getUpcoming"),
];
